SELECT DISTINCT TOP 100
    bl.BL_NO AS 'BL NO',
    cntr.CNTR_NO AS 'CNTR NO',
    cntr.CNTR_TPSZ_CD AS 'CNTR_TPSZ_CD',
    cntr.CGO_PCK_QTY AS 'CGO_PCK_QTY',
    cntr.CGO_PCK_UT AS 'CGO_PCK_UT',
    cntr.CGO_WGT AS 'CGO_WGT',
    cntr.CGO_MEAS AS 'CGO_MEAS',
    bl.POL_NM AS 'POL',
    bl.ETD_DT_TM AS 'ETD',
    updt.ACT_ETD_DT_TM AS 'UPDATED ETD',
    bl.POD_NM AS 'POD',
    bl.ETA_DT_TM AS 'ETA',
    updt.ACT_ETA_DT_TM AS 'UPDATED ETA',
    bl.TRNK_VSL_NM AS 'VESSEL',
    bl.TRNK_VOY AS 'VOYAGE',
    bl.MODI_TMS AS 'BL LAST UPDATED'

FROM TB_INTG_BL bl

JOIN TB_BL_PRNR prnr
ON bl.INTG_BL_SEQ = prnr.INTG_BL_SEQ

JOIN TB_ADD_INFO_BND updt
ON prnr.INTG_BL_SEQ = updt.INTG_BL_SEQ

JOIN TB_CNTR_LIST cntr
ON updt.INTG_BL_SEQ = cntr.INTG_BL_SEQ

WHERE prnr.TRDP_NM = 'DAS COMPANIES INC'

ORDER BY bl.ETA_DT_TM DESC, CNTR_NO ASC

-- SELECT POL_NM, POD_NM, ETD_DT_TM, ETA_DT_TM, POR_NM, TRNK_VOY, TRNK_VSL_NM
-- FROM TB_INTG_BL a
-- JOIN TB_BL_PRNR b
-- ON a.INTG_BL_SEQ = b.INTG_BL_SEQ AND (b.TRDP_CD = 'NTR1002694' OR b.TRDP_CD = 'T37700852' OR b.TRDP_CD = 'T37700853' OR b.TRDP_CD = 'T37700854')
